apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mern-cert
  namespace: default
spec:
  secretName: mern-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: 35.233.67.45
  ipAddresses:
  - 35.233.67.45
  duration: 8760h
  renewBefore: 720h
